# SITE CONFIGURATION
baseurl: ""
url: "https://nickchen120235.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Nick手札
description: Nick的雜七雜八筆記
avatar: assets/img/flight.png
favicon: assets/favicon.ico

# Header and footer text
header_text: >
  I'm not even a procrastinator anymore. I just don't do it at all.
  <h3><a href=https://twitter.com/sally_amaki/status/1615908551553323008 style="color: white">天城サリー 2023.01.19</a></h3>
# header_feature_image: assets/img/pexels/triangular.jpeg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>
  <div>Avatar icon made by <a href="" title="surang">surang</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  cusdis_app_id: 7d9490ed-ac11-494e-bf6c-262c3683f581

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
# collections:
#   portfolio:
#     output: true
#     permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
